/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:7c4ac6f7-cfc8-41d6-bcd5-95dc41d5dc2a",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_a2zGutkk0",
    "aws_user_pools_web_client_id": "7bfplctijvq9v0ab4qparguvdb",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://5pgle6p3yzdjtlh4bziqa46cb4.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-lexumvly2zbinidl2s27srrfem",
    "aws_user_files_s3_bucket": "my-content-provider220543-dev",
    "aws_user_files_s3_bucket_region": "ap-south-1"
};


export default awsmobile;
